# To get started with security, check out the documentation:
# http://symfony.com/doc/current/security.html
security:
    encoders:
        AppBundle\Entity\User:
            algorithm: bcrypt
    # http://symfony.com/doc/current/security.html#b-configuring-how-users-are-loaded
    providers:
        db:
            entity:
                class: AppBundle:User

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        # dev:
            # pattern: ^/(_(profiler|wdt)|css|images|js)/
            # security: false

        main:
            anonymous: true
            provider: db
            pattern: ^/
            form_login:
                login_path: login
                check_path: login
                default_target_path: homepage
            logout:
                path: /logout
                target: homepage
            # activate different ways to authenticate

            # http_basic: ~
            # http://symfony.com/doc/current/security.html#a-configuring-how-your-users-will-authenticate

            # form_login: ~
            # http://symfony.com/doc/current/cookbook/security/form_login_setup.html
    role_hierarchy:
        ROLE_ADMIN: [ROLE_USER]
    access_control:
#        - { path: ^/admin/, roles: ROLE_ADMIN }        